// The one thing about the display that the *project* decides rather than the
// board: which way up the UI is designed.
//
// Emitted as a strong definition over the weak default in each board's
// board_display.c, the same contract hmi_runtime_config uses
// (hmiBindingGenerator.ts). Data rather than a preprocessor define, so both
// orientations are compiled and type-checked in every build instead of one of
// them being invisible to the compiler — and so a firmware template with no
// generated source at all still links and runs, in its default orientation.
//
// See docs/display-orientation.md §9.

import type { DisplayOrientation } from '../types/hmi';

export type GeneratedDisplayConfig = Record<string, string>;

const ORIENTATION_SYMBOLS: Record<DisplayOrientation, string> = {
  landscape: 'HMI_DISPLAY_ORIENTATION_LANDSCAPE',
  portrait: 'HMI_DISPLAY_ORIENTATION_PORTRAIT',
};

function generateHeader(): string {
  return `// Generated by LVGL HMI RAD Tool. Do not edit.
#ifndef HMI_DISPLAY_GENERATED_H
#define HMI_DISPLAY_GENERATED_H

/* hmi_display_config_t and the weak default live here, per board. */
#include "board_display.h"

extern const hmi_display_config_t hmi_display_config;

#endif /* HMI_DISPLAY_GENERATED_H */
`;
}

function generateSource(orientation: DisplayOrientation): string {
  return `// Generated by LVGL HMI RAD Tool. Do not edit.
#include "hmi_display_generated.h"

/*
 * Overrides the __weak default in board_display.c. board_display_init reads
 * this before it creates the LVGL display, so it has to be initialised at
 * compile time — which a const with a static initialiser is.
 */
const hmi_display_config_t hmi_display_config = {
    .orientation = ${ORIENTATION_SYMBOLS[orientation]},
};
`;
}

export function generateDisplayConfig(
  orientation: DisplayOrientation,
): GeneratedDisplayConfig {
  return {
    'hmi_display_generated.h': generateHeader(),
    'hmi_display_generated.c': generateSource(orientation),
  };
}
