// Font Converter for LVGL
// Note: Full font conversion requires lv_font_conv or similar tool
// This provides basic font management and C code generation structure

import type { CharsetType, FontConversionOptions, CharsetPreset } from '../types';

export interface ConvertedFont {
  cCode: string;
  glyphCount: number;
  sizes: number[];
}

/**
 * Get character ranges for charset type
 */
export function getCharsetRanges(
  charset: CharsetType,
  customChars?: string,
  presets?: CharsetPreset[]
): [number, number][] {
  const charsetPresets = presets || [
    { id: 'ascii', ranges: [[32, 126]] },
    { id: 'latin', ranges: [[32, 126], [160, 591]] },
    { id: 'cjk-basic', ranges: [[32, 126], [0x4E00, 0x9FFF]] },
    { id: 'custom', ranges: [] },
  ] as CharsetPreset[];

  if (charset === 'custom' && customChars) {
    // Convert custom characters to ranges
    const codePoints = Array.from(new Set(
      Array.from(customChars).map(c => c.codePointAt(0) || 0)
    )).sort((a, b) => a - b);
    
    // Group consecutive code points into ranges
    const ranges: [number, number][] = [];
    let start = codePoints[0];
    let end = codePoints[0];
    
    for (let i = 1; i < codePoints.length; i++) {
      if (codePoints[i] === end + 1) {
        end = codePoints[i];
      } else {
        ranges.push([start, end]);
        start = codePoints[i];
        end = codePoints[i];
      }
    }
    ranges.push([start, end]);
    
    return ranges;
  }
  
  const preset = charsetPresets.find(p => p.id === charset);
  return (preset?.ranges || [[32, 126]]) as [number, number][];
}

/**
 * Count glyphs in charset
 */
export function countGlyphs(ranges: [number, number][]): number {
  return ranges.reduce((sum, [start, end]) => sum + (end - start + 1), 0);
}

/**
 * Extract unique characters from text
 */
export function extractCharsFromText(text: string): string {
  const chars = new Set(text);
  // Always include basic ASCII printable characters
  for (let i = 32; i <= 126; i++) {
    chars.add(String.fromCharCode(i));
  }
  return Array.from(chars).sort().join('');
}

/**
 * Generate font C code header (placeholder structure)
 * Note: Actual glyph data generation requires bitmap rendering
 */
export function generateFontCCodeHeader(
  name: string,
  family: string,
  size: number,
  options: FontConversionOptions
): string {
  const ranges = getCharsetRanges(options.charset, options.customChars);
  const glyphCount = countGlyphs(ranges);
  
  const rangeStr = ranges
    .map(([start, end]) => `0x${start.toString(16).toUpperCase()}-0x${end.toString(16).toUpperCase()}`)
    .join(', ');

  return `/**
 * Font: ${name}
 * Family: ${family}
 * Size: ${size}px
 * BPP: ${options.bpp}
 * Glyph count: ${glyphCount}
 * Ranges: ${rangeStr}
 * Generated by LVGL UI Editor
 * 
 * NOTE: This is a header template. Full font conversion requires
 * lv_font_conv tool or equivalent bitmap font generator.
 */

#ifndef ${name.toUpperCase()}_H
#define ${name.toUpperCase()}_H

#include "lvgl.h"

LV_FONT_DECLARE(${name});

#endif /* ${name.toUpperCase()}_H */
`;
}

/**
 * Generate font conversion command for lv_font_conv
 */
export function generateFontConvCommand(
  fontFile: string,
  outputName: string,
  options: FontConversionOptions
): string {
  const ranges = getCharsetRanges(options.charset, options.customChars);
  const rangeArgs = ranges
    .map(([start, end]) => `--range=0x${start.toString(16)}-0x${end.toString(16)}`)
    .join(' ');
  
  const sizeArgs = options.sizes.map(s => `--size=${s}`).join(' ');
  
  return `lv_font_conv \\
  --font "${fontFile}" \\
  ${sizeArgs} \\
  --bpp=${options.bpp} \\
  ${rangeArgs} \\
  --format=lvgl \\
  --output="${outputName}.c" \\
  ${options.compress ? '--compress' : '--no-compress'}`;
}

/**
 * Parse font file and extract metadata
 */
export async function parseFontMetadata(base64Data: string): Promise<{
  family: string;
  style: string;
  unitsPerEm: number;
}> {
  // Basic TTF/OTF header parsing
  // This is a simplified version - full parsing would require opentype.js or similar
  
  try {
    // Decode base64 to array buffer
    const binaryString = atob(base64Data.replace(/^data:[^;]+;base64,/, ''));
    const bytes = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
      bytes[i] = binaryString.charCodeAt(i);
    }
    
    // Check for TTF/OTF magic numbers
    const magic = String.fromCharCode(bytes[0], bytes[1], bytes[2], bytes[3]);
    const isValidFont = magic === '\x00\x01\x00\x00' || // TTF
                        magic === 'OTTO' ||              // OTF
                        magic === 'true' ||              // TrueType
                        magic === 'typ1';                // Type 1
    
    if (!isValidFont) {
      throw new Error('Invalid font file format');
    }
    
    // Return placeholder metadata
    // Full implementation would parse name table
    return {
      family: 'Unknown',
      style: 'Regular',
      unitsPerEm: 1000,
    };
  } catch (error) {
    console.error('Failed to parse font:', error);
    return {
      family: 'Unknown',
      style: 'Regular',
      unitsPerEm: 1000,
    };
  }
}

/**
 * Convert font file to base64
 */
export function fontFileToBase64(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    
    reader.onload = () => {
      const result = reader.result as string;
      resolve(result);
    };
    
    reader.onerror = () => {
      reject(new Error('Failed to read font file'));
    };
    
    reader.readAsDataURL(file);
  });
}

/**
 * Default font conversion options
 */
export const DEFAULT_FONT_OPTIONS: FontConversionOptions = {
  sizes: [16],
  charset: 'ascii',
  bpp: 4,
  compress: false,
};

/**
 * Common font sizes for UI
 */
export const COMMON_FONT_SIZES = [8, 10, 12, 14, 16, 18, 20, 24, 28, 32, 36, 48, 64];

/**
 * Preview text for font display
 */
export const FONT_PREVIEW_TEXT = 'The quick brown fox jumps over the lazy dog. 0123456789';
export const FONT_PREVIEW_TEXT_CJK = '中文字体预览 日本語フォント 한국어 글꼴';
