// Image to C Array Converter for LVGL

import type { ImageFormat, ImageConversionOptions } from '../types';

export interface ConvertedImage {
  cCode: string;
  dataSize: number;
  width: number;
  height: number;
  format: ImageFormat;
}

/**
 * Get LVGL color format constant (v8)
 */
function getLvglColorFormatV8(format: ImageFormat, hasAlpha: boolean): string {
  switch (format) {
    case 'RGB565':
      return 'LV_IMG_CF_TRUE_COLOR';
    case 'RGB888':
      return hasAlpha ? 'LV_IMG_CF_TRUE_COLOR_ALPHA' : 'LV_IMG_CF_TRUE_COLOR';
    case 'ARGB8888':
      return 'LV_IMG_CF_TRUE_COLOR_ALPHA';
    default:
      return 'LV_IMG_CF_TRUE_COLOR';
  }
}

/**
 * Get LVGL v9 color format constant
 */
function getLvglColorFormatV9(format: ImageFormat): string {
  switch (format) {
    case 'RGB565':
      return 'LV_COLOR_FORMAT_RGB565';
    case 'RGB888':
      return 'LV_COLOR_FORMAT_RGB888';
    case 'ARGB8888':
      return 'LV_COLOR_FORMAT_ARGB8888';
    default:
      return 'LV_COLOR_FORMAT_ARGB8888';
  }
}

/**
 * Get bytes per pixel for format
 */
function getBytesPerPixel(format: ImageFormat): number {
  switch (format) {
    case 'RGB565':
      return 2;
    case 'RGB888':
      return 3;
    case 'ARGB8888':
      return 4;
    default:
      return 4;
  }
}

/**
 * Convert RGB to RGB565
 */
function rgbToRgb565(r: number, g: number, b: number, swapBytes: boolean): [number, number] {
  const r5 = (r >> 3) & 0x1F;
  const g6 = (g >> 2) & 0x3F;
  const b5 = (b >> 3) & 0x1F;
  
  const rgb565 = (r5 << 11) | (g6 << 5) | b5;
  
  if (swapBytes) {
    return [(rgb565 >> 8) & 0xFF, rgb565 & 0xFF];
  }
  return [rgb565 & 0xFF, (rgb565 >> 8) & 0xFF];
}

/**
 * Convert image data to specified format
 */
function convertPixelData(
  imageData: ImageData,
  format: ImageFormat,
  options: ImageConversionOptions
): Uint8Array {
  const { width, height, data } = imageData;
  const bpp = getBytesPerPixel(format);
  const outputSize = width * height * bpp;
  const output = new Uint8Array(outputSize);
  
  let outIdx = 0;
  
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const idx = (y * width + x) * 4;
      const r = data[idx];
      const g = data[idx + 1];
      const b = data[idx + 2];
      const a = data[idx + 3];
      
      switch (format) {
        case 'RGB565': {
          const [b1, b2] = rgbToRgb565(r, g, b, options.swapBytes);
          output[outIdx++] = b1;
          output[outIdx++] = b2;
          break;
        }
        case 'RGB888': {
          output[outIdx++] = b;
          output[outIdx++] = g;
          output[outIdx++] = r;
          break;
        }
        case 'ARGB8888': {
          output[outIdx++] = b;
          output[outIdx++] = g;
          output[outIdx++] = r;
          output[outIdx++] = a;
          break;
        }
      }
    }
  }
  
  return output;
}

/**
 * Format byte array as C code
 */
function formatAsCArray(data: Uint8Array, bytesPerLine: number = 16): string {
  const lines: string[] = [];
  
  for (let i = 0; i < data.length; i += bytesPerLine) {
    const chunk = Array.from(data.slice(i, i + bytesPerLine));
    const hexValues = chunk.map(b => `0x${b.toString(16).padStart(2, '0').toUpperCase()}`);
    lines.push('    ' + hexValues.join(', ') + ',');
  }
  
  return lines.join('\n');
}

/**
 * Generate C code for LVGL image
 */
export function generateImageCCode(
  name: string,
  imageData: ImageData,
  options: ImageConversionOptions,
  lvglVersion: '8' | '9' = '9'
): ConvertedImage {
  const { width, height } = imageData;
  const pixelData = convertPixelData(imageData, options.format, options);
  const dataSize = pixelData.length;
  
  const dataArrayName = `${name}_data`;
  const dataArray = formatAsCArray(pixelData);

  let cCode: string;

  if (lvglVersion === '9') {
    const cfFormat = getLvglColorFormatV9(options.format);
    const stride = width * getBytesPerPixel(options.format);
    cCode = `/**
 * Image: ${name}
 * Size: ${width}x${height}
 * Format: ${options.format}
 * Data size: ${dataSize} bytes
 * Generated by LVGL UI Editor
 */

#include "lvgl.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

#ifndef LV_ATTRIBUTE_IMG_${name.toUpperCase()}
#define LV_ATTRIBUTE_IMG_${name.toUpperCase()}
#endif

static LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_IMG_${name.toUpperCase()} const uint8_t ${dataArrayName}[] = {
${dataArray}
};

const lv_image_dsc_t ${name} = {
    .header = {
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = ${cfFormat},
        .flags = 0,
        .w = ${width},
        .h = ${height},
        .stride = ${stride},
    },
    .data_size = ${dataSize},
    .data = ${dataArrayName},
};
`;
  } else {
    const hasAlpha = options.format === 'ARGB8888';
    const cfFormat = getLvglColorFormatV8(options.format, hasAlpha);
    cCode = `/**
 * Image: ${name}
 * Size: ${width}x${height}
 * Format: ${options.format}
 * Data size: ${dataSize} bytes
 * Generated by LVGL UI Editor
 */

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

#ifndef LV_ATTRIBUTE_IMG_${name.toUpperCase()}
#define LV_ATTRIBUTE_IMG_${name.toUpperCase()}
#endif

static LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_IMG_${name.toUpperCase()} const uint8_t ${dataArrayName}[] = {
${dataArray}
};

const lv_img_dsc_t ${name} = {
    .header = {
        .cf = ${cfFormat},
        .always_zero = 0,
        .reserved = 0,
        .w = ${width},
        .h = ${height},
    },
    .data_size = ${dataSize},
    .data = ${dataArrayName},
};
`;
  }

  return {
    cCode,
    dataSize,
    width,
    height,
    format: options.format,
  };
}

/**
 * Load image from base64 and get ImageData
 */
export async function loadImageFromBase64(base64Data: string): Promise<{
  imageData: ImageData;
  width: number;
  height: number;
}> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      
      const ctx = canvas.getContext('2d');
      if (!ctx) {
        reject(new Error('Failed to get canvas context'));
        return;
      }
      
      ctx.drawImage(img, 0, 0);
      const imageData = ctx.getImageData(0, 0, img.width, img.height);
      
      resolve({
        imageData,
        width: img.width,
        height: img.height,
      });
    };
    
    img.onerror = () => {
      reject(new Error('Failed to load image'));
    };
    
    // Handle both raw base64 and data URL
    if (base64Data.startsWith('data:')) {
      img.src = base64Data;
    } else {
      img.src = `data:image/png;base64,${base64Data}`;
    }
  });
}

/**
 * Convert image file to base64
 */
export function fileToBase64(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    
    reader.onload = () => {
      const result = reader.result as string;
      resolve(result);
    };
    
    reader.onerror = () => {
      reject(new Error('Failed to read file'));
    };
    
    reader.readAsDataURL(file);
  });
}

/**
 * Get image dimensions from base64
 */
export async function getImageDimensions(base64Data: string): Promise<{
  width: number;
  height: number;
}> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    
    img.onload = () => {
      resolve({
        width: img.width,
        height: img.height,
      });
    };
    
    img.onerror = () => {
      reject(new Error('Failed to load image'));
    };
    
    if (base64Data.startsWith('data:')) {
      img.src = base64Data;
    } else {
      img.src = `data:image/png;base64,${base64Data}`;
    }
  });
}

/**
 * Default conversion options
 */
export const DEFAULT_IMAGE_OPTIONS: ImageConversionOptions = {
  format: 'ARGB8888',
  dither: false,
  compress: false,
  swapBytes: false,
};
